---
- hosts: all
  user: vagrant
  sudo: yes
  vars_files:
    - vars/defaults.yml
  roles:
    - webserver
  # tasks:
  #   - name: ruby-from-src | ensure directory temporary ruby download directory is present
  #     file: state=directory path={{rubyTmpDir}}

  #   - name: ruby-install-src | download
  #     command: wget -O {{rubyIntsallCompressedFile}} {{rubyInstallUrl}} chdir={{rubyTmpDir}}
  #   - name: list
  #     command: ls -l chdir={{rubyTmpDir}}
  #   - name: ruby-install-src | ensure ruby install is extracted
  #     command: tar -xzvf {{rubyIntsallCompressedFile}} chdir={{rubyTmpDir}} creates={{tmpRubyInstallPath}}

  #   - name: ruby-install-src | ensure ruby install is installed
  #     command: sudo make install chdir={{tmpRubyInstallPath}}
  #   - name: Intsall ruby 2.2
  #     command: ruby-install ruby 2.2 creates=/usr/local/bin/rubyUrl
  # tasks:
  #   - name: upgrade
  #     action: apt update_cache=yes upgrade=y
  #   - name: install ruby dependencies
  #     action: apt pkg={{item}} state=installed
  #     with_items:
  #       - build-essential
  #       - automake
