---
- hosts: survey
  user: vagrant
  sudo: yes
  vars_files:
    - vars/defaults.yml
  vars:
    delete_default_vhost: false
    user: www-data
    worker_processes: 16
    pid: /var/run/nginx.pid
    worker_connections: 768
  roles:
    - common
    - webserver