---
- name: bundle install
  command: bundle install --deployment --without="development test"
  args:
    chdir: '{{deploy_directory}}/current'
- name: migrate database
  command: bundle exec rake db:migrate chdir={{deploy_directory}}/current
  environment:
    RAILS_ENV: '{{ rails_env }}'
- name: Precompile assets
  command: bundle exec rake assets:precompile chdir={{deploy_directory}}/current
  environment:
    RAILS_ENV: '{{ rails_env }}'

- name: Restart puma-manager
  action: service name=puma-manager state=restarted
